---
platform: linux
image_resource:
  type: registry-image
  source:
    repository: 18fgsa/concourse-task

inputs:
- name: registry-source
- name: registry-image
- name: ci-source

run:
  path: ci-source/ci/tasks/deploy-registry.sh

params:
  CF_API:
  CF_USERNAME:
  CF_PASSWORD:
  CF_ORG:
  CF_SPACE:
  MIRROR_HOSTNAME:
