---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: 18fgsa/concourse-task

inputs:
- name: source

run:
  path: source/ci/tasks/test-no-push.sh

params:
  MIRROR_HOSTNAME:
